# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend CI Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'CountryApi/**'
      - 'CountryApi.Tests/**'
      - 'CountryApi.sln'
  pull_request:
    branches: [ master ]
    paths:
      - 'CountryApi/**'
      - 'CountryApi.Tests/**'
      - 'CountryApi.sln'

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'CountryApi.sln'
  API_PROJECT: 'CountryApi/CountryApi.csproj'
  TEST_PROJECT: 'CountryApi.Tests/CountryApi.Tests.csproj'

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    
    - name: Build Solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          CountryApi/bin/Release
          CountryApi.Tests/bin/Release
        retention-days: 1

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: build-output
    
    - name: Run Unit Tests
      run: dotnet test ${{ env.TEST_PROJECT }} --configuration Release --no-build --verbosity normal

  package:
    name: Package Application
    needs: test  # Depends on successful tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    
    - name: Publish Application
      run: |
        mkdir -p ./publish
        dotnet publish ${{ env.API_PROJECT }} \
          -c Release \
          -o ./publish \
          --no-restore \
          /p:Version=1.0.${{ github.run_number }}
    
    - name: Create ZIP Package
      run: |
        cd ./publish
        zip -r ../${{ env.PACKAGE_NAME }}.zip .
        cd ..
    
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}-package
        path: ${{ env.PACKAGE_NAME }}.zip
        retention-days: 7   
