# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend CI Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'CountryApi/**'  
  pull_request:
    branches: [ master ]
    paths:
      - 'CountryApi/**'

env:
  DOTNET_VERSION: '8.0.x'  
  SOLUTION_FILE: 'FlagApp/CountryApi.sln'  
  API_PROJECT: 'FlagApp/CountryApi/CountryApi.csproj' 
  TEST_PROJECT: 'FlagApp/CountryApi.Tests/CountryApi.Tests.csproj'  

jobs:
  build:
    name: Build CountryApi
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          CountryApi/**/bin/Release
          CountryApi/**/obj/Release
        retention-days: 1
    
