name: Frontend CI

on:
  push:
    branches: [master]
    paths:
      - 'country-frontend/**'

env:
  NODE_VERSION: '18.x'
  PROJECT_DIR: 'country-frontend'

jobs:
  build-and-package:
    name: Build & Package
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    
    - name: Install & Build
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        npm ci
        npm run build
    
    - name: Create ZIP Package
      run: |
        cd ${{ env.PROJECT_DIR }}/dist
        zip -r ../../frontend-pkg-${{ github.run_number }}.zip .
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-package
        path: frontend-pkg-*.zip
        retention-days: 7
