name: Frontend CI: Build & Package

on:
  push:
    branches: [master]
    paths:
      - 'country-frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'country-frontend/**'

env:
  NODE_VERSION: '18.x'
  PROJECT_DIR: 'country-frontend'

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    
    - name: Install & Build
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        npm ci
        npm run build
        
      # Verify build directory exists
      if: |
        echo "Checking build directory..."
        ls -la ${{ env.PROJECT_DIR }}/build
        
    - name: Prepare Artifact
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        echo "Current directory: $(pwd)"
        echo "Build contents:"
        ls -la build/
        
        mkdir -p ../artifact
        cp -r build/* ../artifact/
        echo "Artifact contents:"
        ls -la ../artifact/
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: artifact
        retention-days: 1

  package:
    name: Package Stage
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: artifact
    
    - name: Verify Download
      run: |
        echo "Downloaded artifacts:"
        ls -la artifact/
        du -sh artifact/
    
    - name: Create ZIP Package
      run: |
        cd artifact
        zip -r ../frontend-pkg-${{ github.run_number }}.zip .
    
    - name: Upload Final Package
      uses: actions/upload-artifact@v4
      with:
        name: frontend-package
        path: frontend-pkg-*.zip
        retention-days: 7
