# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI/CD

on:
  push:
    branches: [master]
    paths:
      - 'country-frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'country-frontend/**'

env:
  NODE_VERSION: '18.x'
  PROJECT_DIR: 'country-frontend'
  
jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    - name: Install dependencies
      working-directory: ${{ env.PROJECT_DIR }}  # All commands run in frontend dir
      run: npm ci  # Uses package-lock.json from country-frontend/
    
    - name: Run production build
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm run build
    
    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ${{ env.PROJECT_DIR }}/build
        retention-days: 1

  package:
    name: Package Stage
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        
    - name: Create ZIP package
      run: |
        cd build  # Now in country-frontend/build after download
        zip -r ../frontend-pkg-${{ github.run_number }}.zip .
        
    - name: Upload final package
      uses: actions/upload-artifact@v4
      with:
        name: frontend-package
        path: ${{ env.PROJECT_DIR }}/frontend-pkg-*.zip
