name: Frontend CI

on:
  push:
    branches: [master]
    paths:
      - 'country-frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'country-frontend/**'

env:
  NODE_VERSION: '18.x'
  PROJECT_DIR: 'country-frontend'
  BUILD_OUTPUT_DIR: 'country-frontend/dist'  # Changed to Vite's output dir

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    
    - name: Install dependencies
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm ci
    
    - name: Build production
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        npm run build
        echo "Vite build output:"
        ls -la dist/  # Verify Vite's output directory
        
    - name: Prepare artifact
      run: |
        echo "Copying from: ${{ env.BUILD_OUTPUT_DIR }}"
        ls -la ${{ env.BUILD_OUTPUT_DIR }}
        
        mkdir -p artifact
        cp -r ${{ env.BUILD_OUTPUT_DIR }}/* artifact/
        echo "Artifact contents:"
        ls -la artifact/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: artifact
        retention-days: 1

  package:
    name: Package Stage
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: artifact
    
    - name: Create ZIP package
      run: |
        cd artifact
        zip -r ../frontend-pkg-$
