name: Frontend

on:
  push:
    branches: [master]
    paths:
      - 'country-frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'country-frontend/**'

env:
  NODE_VERSION: '18.x'
  PROJECT_DIR: 'country-frontend'
  BUILD_OUTPUT_DIR: 'country-frontend/dist'

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    
    - name: Install & Build
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        npm ci
        npm run build
        echo "Build output:"
        ls -la dist/

    # Only outputs the dist directory without uploading artifact
    - name: Preserve build output
      run: |
        echo "BUILD_OUTPUT_PATH=${{ env.BUILD_OUTPUT_DIR }}" >> $GITHUB_ENV

  test:
    name: Test Stage
    needs: build  # Runs after build completes
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json
    
    - name: Install dependencies
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm ci
    
    - name: Run tests
      working-directory: ${{ env.PROJECT_DIR }}
      run: npm test -- --run
      # Alternative with coverage:
      # run: npm run test:coverage

  package:
    name: Package Stage
    needs: test  # Now depends on test stage passing
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Recreate build output
      run: |
        echo "Rebuilding in package stage..."
        cd ${{ env.PROJECT_DIR }}
        npm ci
        npm run build
        ls -la dist/
    
    - name: Create ZIP package
      run: |
        cd ${{ env.BUILD_OUTPUT_DIR }}
        zip -r ../../frontend-pkg-${{ github.run_number }}.zip .
    
    - name: Upload final package
      uses: actions/upload-artifact@v4
      with:
        name: frontend-package
        path: frontend-pkg-*.zip
        retention-days: 7
